-- AlterTable
ALTER TABLE "ExchangeRate"
ADD COLUMN "provider" TEXT NOT NULL DEFAULT 'seed',
ADD COLUMN "midMarketRate" DECIMAL(18,6) NOT NULL DEFAULT 0,
ADD COLUMN "spread" DECIMAL(10,6) NOT NULL DEFAULT 0,
ADD COLUMN "isLive" BOOLEAN NOT NULL DEFAULT false;
